name: Bump

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cat ./package.json
      - uses: 'phips28/gh-action-bump-version@master'
        id: version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        with:
          tag-prefix: 'v'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
      - run: echo "new tag $NEW_TAG"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
